appartement:
  - ""
salle de bain:
  - https://cdn-icons-png.flaticon.com/128/5489/5489134.png
  - https://cdn-icons-png.flaticon.com/128/7591/7591354.png
  - https://cdn-icons-png.flaticon.com/128/2642/2642330.png
  - https://cdn-icons-png.flaticon.com/128/843/843965.png
  - https://cdn-icons-png.flaticon.com/128/2789/2789594.png
  - https://cdn-icons-png.flaticon.com/128/3877/3877208.png
  - https://cdn-icons-png.flaticon.com/128/5489/5489134.png
  - https://cdn-icons-png.flaticon.com/128/7591/7591354.png
  - https://cdn-icons-png.flaticon.com/128/1739/1739026.png
  - https://cdn-icons-png.flaticon.com/128/531/531017.png
  - https://cdn-icons-png.flaticon.com/128/5513/5513105.png
salle eau:
  - ""
chambre:
  - https://cdn-icons-png.flaticon.com/128/2642/2642268.png
  - https://cdn-icons-png.flaticon.com/128/2652/2652612.png
  - https://cdn-icons-png.flaticon.com/128/7726/7726218.png
  - https://cdn-icons-png.flaticon.com/128/896/896455.png
surface:
  - ""
biens:
  - ""

terrain:
  - "https://cdn-icons-png.flaticon.com/128/7012/7012489.png"
  - "https://cdn-icons-png.flaticon.com/128/7896/7896888.png"
  - "https://cdn-icons-png.flaticon.com/128/7896/7896893.png"
  - "https://cdn-icons-png.flaticon.com/128/7896/7896890.png"