appartement:
salle de bain:
  img: https://cdn-icons-png.flaticon.com/128/5489/5489134.png
  img: https://cdn-icons-png.flaticon.com/128/7591/7591354.png
  img: https://cdn-icons-png.flaticon.com/128/2642/2642330.png
salle eau:
chambre:
surface:
biens:
