Bourse:
  url: bourse
  cover: quartiers/petite-france.png
Centre-ville:
  url: centre-ville
  cover: quartiers/petite-france.png
Conseil des XV:
  url: conseil-des-xv
  cover: quartiers/petite-france.png
Cronenbourg:
  url: cronenbourg
  cover: quartiers/petite-france.png
Elsau:
  url: elsau
  cover: quartiers/petite-france.png
Esplanade:
  url: esplanade
  cover: quartiers/petite-france.png
Ganzau:
  url: ganzau
  cover: quartiers/petite-france.png
Gare:
  url: gare
  cover: quartiers/petite-france.png
Hautepierre:
  url: hautepierre
  cover: quartiers/krutenau.png
Koenigshoffen:
  url: koenigshoffen
  cover: quartiers/petite-france.png
Krutenau:
  url: krutenau
  cover: quartiers/krutenau.png
Meinau:
  url: meinau
  cover: quartiers/krutenau.png
Montagne Verte:
  url: montagne-verte
  cover: quartiers/krutenau.png
Musau:
  url: musau
  cover: quartiers/krutenau.png
Neudorf:
  url: neudorf
  cover: quartiers/krutenau.png
Neuhof:
  url: neuhof
  cover: quartiers/krutenau.png
Orangerie:
  url: orangerie
  cover: quartiers/krutenau.png
Petite France:
  url: petite-france
  cover: quartiers/petite-france.png
  text: <p>
            Le quartier de la <strong>Petite France</strong> offre un véritable voyage dans le temps, où chaque bâtisse raconte une histoire riche et fascinante. Les façades romantiques reflètent l'empreinte des siècles passés, tandis que les petits ponts enjambant les canaux ajoutent une touche de poésie à l'ensemble. La <strong>Petite France</strong> est un tableau vivant, une symphonie d'architecture et de nature, imprégnée de l'essence même de <strong>Strasbourg</strong>.
            <br><br>
            Les restaurants authentiques, les cafés pittoresques et les boutiques d'artisans locaux contribuent à l'ambiance conviviale de ce quartier, créant un véritable art de vivre.
        </p>
Poteries:
  url: poteries
  cover: quartiers/krutenau.png
Port du Rhin:
  url: port-du-rhin
  cover: quartiers/krutenau.png
Presqu’île Malraux:
  url: presqu-ile-malraux
  cover: quartiers/presqu-ile-malraux.png
Robertsau:
  url: robertsau
  cover: quartiers/krutenau.png
Stockfeld:
  url: stockfeld
  cover: quartiers/krutenau.png
Tribunal:
  url: tribunal
  cover: quartiers/krutenau.png
Wacken:
  url: wacken
  cover: quartiers/krutenau.png